### ISSUE TITLE
副本板块BOSS排序需要修正

### ISSUE THREAD

**Issue by ghost** [JX3BOX/fb#10]
按照官方的设定，副本BOSS的排序应该为【周贽、厌夜、迟驻、白某、安小逢】
技能数据板块的【潜行】属于副本的跳老1剧情任务物品的任务，应该排序在最前面。

![Snipaste_2020-05-28_22-52-53.png](https://i.loli.net/2020/05/28/dWAMO7eQc5gNBqI.png)
![Snipaste_2020-05-28_22-50-31.png](https://i.loli.net/2020/05/28/UqTQK8xR7ow3GPk.png)
![Snipaste_2020-05-28_22-52-29.png](https://i.loli.net/2020/05/28/CuBapjxkzFQ6YhM.png)
![Snipaste_2020-05-28_22-58-05.png](https://i.loli.net/2020/05/28/cfqjFGBTepm2Yr7.png)

**Comment by iRuxu** [comment]
当前以安小逢作为焦点。
后面2个可能不会做强制
