### ISSUE TITLE
新版副本掉落大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/fb#18]
为解决推栏掉落时效性以及数据分组异常等问题
构建了新的副本掉落数据表和接口

前端文件：src/views/drop_v2.vue
访问地址：/#/drop_v2  （线上还是旧版本，本地需要访问这个新版地址才是）

**Comment by iRuxu** [comment]
## 单个物品渲染
单个物品的数据，请使用Item公共组件与接口，展示物品浮层
![image](https://user-images.githubusercontent.com/8476969/142158104-78b1de70-c05b-4c0a-8eb9-23473dd2c10e.png)

- [ ] 已完成

**Comment by iRuxu** [comment]
## 支持心法匹配
![image](https://user-images.githubusercontent.com/8476969/142185588-a631896d-fcce-4410-90b2-c15bf97ad4d5.png)

增加一列心法图标+名称，第一个为全部，点击下面的进行过滤
主要为 ApplicableSchoolIDs 字段（此字段数据为**玩家门派 SchoolID**，需要进行心法反查）

- [x] 已完成

**Comment by iRuxu** [comment]
### ApplicableSchoolIDs  说明

使用的是门派school id

此字段为以"|"分隔的玩家门派 SchoolID，定义如下

`var isOk = data["ApplicableSchoolIDs"].split("|").includes(MountIDToSchoolID(mountId))`

|SchoolID|Name|
|-|-|
|0|江湖|
|1|天策|
|2|万花|
|3|纯阳|
|4|七秀|
|5|少林|
|6|藏剑|
|7|丐帮|
|8|明教|
|9|五毒|
|10|唐门|
|18|苍云|
|19|长歌|
|20|霸刀|
|21|蓬莱|
|22|凌雪阁|
|23|衍天宗|
|24|北天药宗|

**Comment by iRuxu** [comment]
目前整体还缺书籍的数据~

**Comment by whc2001** [comment]
> 目前整体还缺书籍的数据~

https://github.com/JX3BOX/jx3-drop/issues/2#issuecomment-971639033
