### ISSUE TITLE
搜索栏不能仅搜索一个副本

### ISSUE THREAD

**Issue by guanyintu** [JX3BOX/fb#2]
![image](https://user-images.githubusercontent.com/37127965/82409454-61887880-9aa0-11ea-980a-0831aa2633c5.png)

**Comment by iRuxu** [comment]
补：只看首领

**Comment by iRuxu** [comment]
@fakedestinyck  后面补充功能由枫瑞接手，做完需要移植一份到剑三数据库应用项目。
https://github.com/JX3BOX/app-db
接口可能要改，根据最终需求给我参数。
