### ISSUE TITLE
副本掉落BUG

### ISSUE THREAD

**Issue by Kaviilee** [JX3BOX/fb#22]
## 除武器和特殊掉落外，其余的物品无法预览

- 武器
![image](https://user-images.githubusercontent.com/25825282/205977028-71f0317d-0aff-4163-840e-45900274cee4.png)

- 其余物品
![image](https://user-images.githubusercontent.com/25825282/205977156-e438ed3b-3e60-4c8d-afa3-fac26148be59.png)

---------
- [x] 已完成

**Comment by Kaviilee** [comment]
## 一个物品请求多次接口
![image](https://user-images.githubusercontent.com/25825282/205977399-d0866f48-d119-40cb-9ece-3cede13757d9.png)

需要优化成只有一次请求

-----------

- [x] 已完成

**Comment by x3zvawq** [comment]
> ## 除武器和特殊掉落外，其余的物品无法预览
> * 武器
>   ![image](https://user-images.githubusercontent.com/25825282/205977028-71f0317d-0aff-4163-840e-45900274cee4.png)
> * 其余物品
>   ![image](https://user-images.githubusercontent.com/25825282/205977156-e438ed3b-3e60-4c8d-afa3-fac26148be59.png)
> 
> * [x]  已完成

目测是同步数据到数据库的时候发生了什么奇怪的事情导致的丢失了一部分

**Comment by x3zvawq** [comment]
> ## 一个物品请求多次接口
> ![image](https://user-images.githubusercontent.com/25825282/205977399-d0866f48-d119-40cb-9ece-3cede13757d9.png)
> 
> 需要优化成只有一次请求
> 
> * [x]  已完成

现在会读到数据之后先把其中所有的物品数据请求到，丢到session。
editor的item组件就不会在需要请求了
@iRuxu  需要部署jx3box-node的最新提交

**Comment by Kaviilee** [comment]
> 

![image](https://user-images.githubusercontent.com/25825282/206687044-be14c96e-1af5-465b-ac37-ed8d8be7cc7e.png)
 仍然存在重复请求
