### ISSUE TITLE
副本3.0

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/fb#26]
![cba4bb9c3b2817bb52598839f90271a7](https://user-images.githubusercontent.com/8476969/224708177-4c3343b5-2a3b-44e3-ba35-593bed58dbfb.jpeg)

## 路由模式
参考macro和bps

+ router中改为history模式
+ post.js和post.vue变成single.vue
+ layouts

- [x] 已完成

**Comment by iRuxu** [comment]
## 左侧边栏-副本导航
<img width="116" alt="image" src="https://user-images.githubusercontent.com/8476969/224643411-fc1df1b9-0562-44e4-b458-8aedc4b5cd8f.png">

1. 下拉选择副本，支持搜索，默认没有值
<img width="320" alt="image" src="https://user-images.githubusercontent.com/8476969/224644283-f8d94ec6-6174-4c8d-a692-cfd0fedee6fd.png">

2. 封面图
__imgPath + json中的图片icon

默认值来自
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/8476969/224645136-532c4497-226c-4a5c-b8c8-ca11e9e8f874.png">

3. 副本基本信息

加粗 ： 副本名称
难度：
<img width="433" alt="image" src="https://user-images.githubusercontent.com/8476969/224645319-0710b032-33bd-4de8-927e-bf32856a5fb2.png">
首领：
<img width="884" alt="image" src="https://user-images.githubusercontent.com/8476969/224645335-9f5ac770-82c2-4d9b-baba-e74a7d36fe2a.png">

4. 子应用
简介、掉落，瑰石、Npc、成就

**Comment by iRuxu** [comment]
## 左侧边栏应用
<img width="293" alt="image" src="https://user-images.githubusercontent.com/8476969/224646124-a0e6c6cc-6ec6-4f90-b259-9ec405bfc49e.png">

日志分析  jcl
团队统计  battle
Boss时间轴 - 
团队平台 team
数据构建 dbm
八荒衡鉴 bahuang
百战查询 baizhan

- [x] 已完成

**Comment by iRuxu** [comment]
## 右侧边栏

1. 参考宏库macro或职业bps这个项目，恢复好右边栏

2. 群号


- [x] 已完成

**Comment by iRuxu** [comment]
## 右边栏-百强榜

<img width="283" alt="image" src="https://user-images.githubusercontent.com/8476969/224646846-e6d2e6ca-a2c0-49d9-8858-d457a128f0c7.png">

`import {getAppIcon} from '@jx3box/jx3box-common/js/utils`

getAppIcon('rank')

查看更多是跳转到 `/rank`

<img width="287" alt="image" src="https://user-images.githubusercontent.com/8476969/224647186-32065b4e-ae97-427a-8f82-4206e6b122c1.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/8476969/224647332-f446a519-fad8-4f8e-8b00-4ebd0c8b566c.png">

通过切换下面榜单跟随变化，默认是现在请求100名，小胡换成  只返回10名

团队logo + 团队名称，点击团队名称跳转到团队主页`/team/org/${id}`

- [x] 已完成

**Comment by iRuxu** [comment]
## 右边栏-团队招募

<img width="297" alt="image" src="https://user-images.githubusercontent.com/8476969/224647812-748842e0-d1d0-484d-855d-fcb6b117a7ea.png">

调用对应团队应用主页的2个接口

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/8476969/224648048-7c80994e-8623-47dc-af4c-145912d66dff.png">


- [x] 已完成

**Comment by iRuxu** [comment]
## tabs
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/8476969/224648611-fa662ca5-4021-4990-92e1-bd71c81e136c.png">

开荒攻略

副本掉落
瑰石列表
副本成就
！！秘境传说（合并副本地图）

首领数据
！！高阶技巧（改名，增加一些高阶攻略的链接）

技能数据（签约）
源码分析（签约）

- [x] 已完成

**Comment by iRuxu** [comment]
## 内容区
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/8476969/224651363-aeb0d453-d911-4cdc-8228-73b38383c017.png">

接口加载同理携带topic参数

- [ ] 已完成

**Comment by iRuxu** [comment]
## 八荒
只有怀旧服有
现在是app/bahuang
https://origin.jx3box.com/app/bhhj/?tab=arcane

迁移合并到这个fb库

参考宏库栏目

<img width="457" alt="image" src="https://user-images.githubusercontent.com/8476969/224651928-f6356218-8ae0-428f-9648-05d23f31eadf.png">


- [x] 已完成

**Comment by iRuxu** [comment]
## 百战

新增一个百战的应用

- [ ] 已完成

**Comment by Kaviilee** [comment]
## 优化
![image](https://user-images.githubusercontent.com/25825282/226164819-c7d0a89b-ab2c-4a6d-b472-392155109c67.png)
需要更优雅的实现

- [ ] 已完成

**Comment by Kaviilee** [comment]
![image](https://user-images.githubusercontent.com/25825282/226164913-4eea6ac8-5fcf-4917-9a79-e4647aa86aaa.png)
可以v-for

- [x] 已完成

**Comment by Kaviilee** [comment]
![image](https://user-images.githubusercontent.com/25825282/226165156-29f8f2c5-b201-4ae2-9b22-37a5dc43a16d.png)
需要优化， $router的写法也需要优化 query

- [ ] 已完成

**Comment by Kaviilee** [comment]
![image](https://user-images.githubusercontent.com/25825282/226165226-7a7e5ec8-0f2e-4b42-bbbd-83a94dd87e05.png)
事件不应该绑定在option上，应该是针对search的改变而做出相应的逻辑

- [ ] 已完成

**Comment by Kaviilee** [comment]
## 关于查询
需要查询副本难度和副本boss时，传参数topic，例如
`api/cms/posts?type=fb&per=10&page=1&subtype=西津渡&order=update&client=std&sticky=1&topic=张景超` ，则查询张景超的文章，不能同时传副本难度和副本boss，前端需要注意select的回显

**Comment by Kaviilee** [comment]
## 天梯榜
1. 应该是跳转到百强榜的页面，用`@jx3box/jx3box-common/js/utils`中的getLink方法获取链接
![image](https://user-images.githubusercontent.com/25825282/227158852-3fa3679c-8daf-4f1b-ae51-e760f13df069.png)

- [x] 已完成

2. 写相对路径，代码中不要出现具体的域名
![image](https://user-images.githubusercontent.com/25825282/227160678-b3d0d478-095f-40ec-8b1b-da314b33c0b4.png)

- [x] 已完成


3. 用 `@jx3box/jx3box-common/js/utils` 中的 `getThumbnail` 方法，不要使用原图，oss很烧钱的
![image](https://user-images.githubusercontent.com/25825282/227161922-ba5f2455-09da-452f-b48c-aa8af07ea648.png)

- [x] 已完成

4. 加载中的效果不需要你自己写，element有loading指令 `v-loading`
![image](https://user-images.githubusercontent.com/25825282/227162418-e0f46858-cf1b-47a6-8f7e-dd755ececa78.png)

- [x] 已完成

5. 可以参照macro的侧边栏加一下排名
![image](https://user-images.githubusercontent.com/25825282/227163084-9494ab9b-c6e5-445a-9652-5bd2fbcb36be.png)

- [x] 已完成

**Comment by Kaviilee** [comment]
## 团队招募
1. 查看更多按钮同楼上

- [x] 已完成

2. 用 `el-button-group`
![image](https://user-images.githubusercontent.com/25825282/227170149-a42bef89-d9ef-43f4-b6e3-25a32386bbb1.png)

- [x] 已完成

**Comment by Kaviilee** [comment]
## list_nav
1. 可读性很差，而且你直接读std，怀旧服怎么办，要用 `client` 去匹配的
![image](https://user-images.githubusercontent.com/25825282/227163830-a2ada104-8f0a-4f40-8b63-8c8953abb661.png)

- [ ] 已完成

2. 移动端适配
![image](https://user-images.githubusercontent.com/25825282/227170433-0cfdde55-7cda-4171-bdec-c0908959a0b2.png)
![image](https://user-images.githubusercontent.com/25825282/227170455-9d537523-bf71-4662-8458-6500def4f0eb.png)

- [ ] 已完成

**Comment by Kaviilee** [comment]
## 秘境传说

1. 合并副本地图，地图呢？
![image](https://user-images.githubusercontent.com/25825282/227170909-a4bea639-c4ec-43e7-967f-e74e59e9ba95.png)

- [x] 已完成
