### ISSUE TITLE
新版百战

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/fb#30]
## 说明

百战出一个玩家可以每周看一眼的东西
之前群里 还有茶馆有很多玩家写过一些东西
都可以参考一下

具体你自己写好后端
前端不想写的话，写一个需求文档，由牧野完成

- [ ] 已完成

**Comment by iRuxu** [comment]
## 反馈
https://www.jx3box.com/dashboard/feedback/562
比如这种，看看副本的右侧边栏，可以拿来放
<img width="1919" alt="image" src="https://github.com/JX3BOX/fb/assets/8476969/acad8ccf-56b5-4ddd-94fd-8a37b0a60386">

反正百战出来后，这里打算放一些和pve其他相关的东西，不再展示百强榜

- [ ] 已完成

**Comment by x3zvawq** [comment]
页面可以参考 
https://www.figma.com/file/28OnUWgiItEcGEBP0daWnL/%E7%99%BE%E6%88%98?type=design&node-id=0-1

游戏内图标资源
[百战图片资源.zip](https://github.com/JX3BOX/fb/files/11858949/default.zip) By 南宫伯

需要实现的功能
- 地图/每层的boss及其buff
- boss信息及攻略
- 技能信息及攻略

**Comment by x3zvawq** [comment]
# 地图相关
- [ ] 需要显示本周百战地图的boss，每一层的buff
- [ ] 用户选择一个首领的时候需要在地图上醒目展示该首领出现的位置
- [ ] 这个需要人工维护，所以前端不仅需要做展示，还需要做一套允许修改的UI
- [ ] 做一个允许查看历史地图的功能以供统计应该很帅，甚至可以做出一个统计，哪个boss出现的最多

**Comment by x3zvawq** [comment]
# boss信息及攻略
- [ ] 页面需要展示boss的信息，比如有哪些npc，npc的技能等。可能也需要人工维护
- [ ] 可以考虑使用wikipost那样子的百科形式，但是需要区分层数，难度（3人，6人，10人等）
- [ ] 如果wikipost不方便的话也可以考虑直接链接到一篇已有的post，这样的话需要在页面留一个管理/编辑可以编辑链接的入口

**Comment by x3zvawq** [comment]
# 技能信息及攻略
- [ ] 需要一个表格，实现游戏里的基础过滤并且添加额外的功能。比如根据各种方式排序
- [ ] 可能会需要人工维护技能的伤害/精耐消耗/精耐打击/读条时间等各种属性
- [ ] 需要类似wiki_post那样的技能攻略
- [ ] 技能脚本lua

**Comment by x3zvawq** [comment]
接口开发中（x

**Comment by x3zvawq** [comment]
前端需要实现的
百战技能查询 
百战技能是独立于玩家技能外的一套体系，可以通过通本升级或者打百战掉落。这些技能有各自的特点，允许在百战中使用

![image](https://github.com/JX3BOX/fb/assets/47066861/ac21a8d3-0bfd-4d75-a301-54a787c14be9)

技能应该要可以展开，允许玩家提交攻略，麻烦的话可以引导向一篇文章

**Comment by x3zvawq** [comment]
百战地图可以参考figma

**Comment by x3zvawq** [comment]
boss信息的话应该跟技能差不多

**Comment by x3zvawq** [comment]
接口
cms/map相关
start 字段 应该这周一 2022-06-22 00:00
data 
```json
[
  {
    ”level“: 1,
    “boss”: "源明雅",
    “effect”: 1
  },
{
    ”level“: 1,
    “boss”: "源明雅",
    “effect”: 1
  }
{
    ”level“: 1,
    “boss”: "源明雅",
    “effect”: 1
  }
]
```

enable: 1
.
![image](https://github.com/JX3BOX/fb/assets/47066861/8916c225-2b99-4fa1-882f-f614ac5be441)

**Comment by x3zvawq** [comment]
boss

![image](https://github.com/JX3BOX/fb/assets/47066861/20fde9dc-3f2c-4f3b-850b-8f5a1b2c3018)

**Comment by x3zvawq** [comment]
![image](https://github.com/JX3BOX/fb/assets/47066861/a7ecb4e6-f761-4270-8c2f-87c26722eff6)



https://cms.jx3box.com/api/cms/app/monster/skill?ids=1141,2560
