### ISSUE TITLE
百战更新

### ISSUE THREAD

**Issue by nierssaxa** [JX3BOX/fb#31]
将百战工具重新定义。

- 地图功能
 1.快速了解本周精英BOSS
 2.快速识别本周特殊格子
 3.快速了解本周特殊格子效果
 4.一键导出图片（看看要不要做） @iRuxu 
 5.筛选功能（特殊格子，特殊BOSS）
 6.可自由放大缩小的百战地图，参考（[https://map.caimogu.cc/d4.html]）主要用于自适应各种PC端显示器分辨率

- 技能数据
罗列百战的技能等之类的数据，和现有的一致即可

- 首领数据
1.展现首领的信息
2.展现首领的技能（看看是否能通过阶级区分技能信息）
3.展现首领在本周地图的位置
~4.添加短评论功能，和奇遇宠物百科一样，人人都可以短暂评论（利用短评论快速让用户了解BOSS打法，节省看大型攻略的时间），点赞~
5.新增按钮导入到现有的百战攻略文章列表页

**Comment by nierssaxa** [comment]
页面布局（通用）

- 去掉面包屑
- 左侧以三个功能为主（可以增加按钮折叠起来，类似于PVX或者文章）
- ~左侧其次以列表的形式展现本周的60层 （主要是左侧不会变，用于辅助用户快速了解本周首领布局）~
- 左侧新增筛选

**Comment by nierssaxa** [comment]
页面布局（地图）

- 左侧
与大局一致不变
~注意层数选择要和地图上的层数联动~

- 中间
1.可自由放大缩小的百战地图，参考（[https://map.caimogu.cc/d4.html]）主要用于自适应各种PC端显示器分辨率
2.所有层数效果可能要换更通俗的方式来解释，如因陀罗的战术，应当采用[图标]前进6步 [图标]骰子减半  [图标]50的形式展示
3.具体样式晚点更新
4.去掉往期百战地图（如果有用户需要再考虑开放入口）
5.左上方新增筛选功能（利用通俗的解释为TAG，如图前进、骰子减半、额外货币等）

- 右侧
1.第一行头像+BOSS名字
~2.第二行BOSS介绍~
~3.第三行BOSS技能（鼠标悬浮功能可以去掉）~
4.可以在右上角加一个按钮跳转到，对应BOSS详细攻略的页面
5.增加掉落招式~鼠标悬浮仅展示名字即可，鼠标左键可以点击可以转到对应数据库信息查询~
~6.讨论评价，不多做叙述~

![image](https://github.com/JX3BOX/fb/assets/97571785/a21066b3-5613-43c1-b48c-0dc77d9b0064)

**Comment by nierssaxa** [comment]
页面布局（技能信息）

- 左侧
不变，可以通过点击层数筛选技能（按照首领）

- 中间
表格

- 右侧
没有右侧

**Comment by nierssaxa** [comment]
页面布局（首领信息-首页）

- 左侧
不变

- 右侧
1.第一段 展示所有BOSS头像，用户可以点击头像进入该BOSS页面
2.第二段 拉取现在副本百战异闻录的文章列表，点击后可以跳转到对应文章

**Comment by nierssaxa** [comment]
页面布局（首领信息-内页）

- 左侧
不变

- 右侧
1.有一个返回的按钮
2.第一段 展示BOSS信息，技能部分为了节省空间，用技能图标做tabview，点击后切换下方的技能信息
3.第二段 展示评论功能

**Comment by fifthThirteen** [comment]
https://www.figma.com/file/28OnUWgiItEcGEBP0daWnL/%E7%99%BE%E6%88%98?type=design&node-id=83-7383&mode=design&t=SfrJrH1VDn7ygqkN-0

**Comment by fifthThirteen** [comment]
/api/cms/app/monster/boss?names=
/api/cms/app/monster/skill?ids=28029,28030,28105,28126,28127,28128,28129,28132,28135,28146,28152,28174,28176,28178,28193,28302,28303,28304,28306,28320,28321,28324,28330,28334,28337,28487,28491,28492,28493,28495,28496,28497,28525,28527,28554,28570,28607,28767,28768,28769,28772,28778,28779,28780,28781,28801,28802,28803,28911,28940,28941,28942,28943,28945,28956,28959,28960,28967,29011,29012,29014,29052,29054,29096,29097,29098,29111,29121,29123,29343,29344,29347,29460,29468,29627,29628,29631,29633,29639,29648,29952,29954,30100,32011,32014,32016,32023,33595,33599,35089,35091,35098,35100,35105,35108,35110,35114
![D~1I AQWMG VO%ERSGGG30S](https://github.com/JX3BOX/fb/assets/30660189/b85bf18c-86e8-49db-b91a-60f05cb66c08)
请求详情信息返回是否有限制。

**Comment by fifthThirteen** [comment]
boss信息是否可以返回简介

**Comment by x3zvawq** [comment]
> /api/cms/app/monster/boss?names= /api/cms/app/monster/skill?ids=28029,28030,28105,28126,28127,28128,28129,28132,28135,28146,28152,28174,28176,28178,28193,28302,28303,28304,28306,28320,28321,28324,28330,28334,28337,28487,28491,28492,28493,28495,28496,28497,28525,28527,28554,28570,28607,28767,28768,28769,28772,28778,28779,28780,28781,28801,28802,28803,28911,28940,28941,28942,28943,28945,28956,28959,28960,28967,29011,29012,29014,29052,29054,29096,29097,29098,29111,29121,29123,29343,29344,29347,29460,29468,29627,29628,29631,29633,29639,29648,29952,29954,30100,32011,32014,32016,32023,33595,33599,35089,35091,35098,35100,35105,35108,35110,35114 ![D~1I AQWMG VO%ERSGGG30S](https://user-images.githubusercontent.com/30660189/255643221-b85bf18c-86e8-49db-b91a-60f05cb66c08.png) 请求详情信息返回是否有限制。

这个没有限制的，只是这些数据需要手动维护 数据库里还没数据所以返回的不全（x 现在能查到的都是之前测试的时候加上的

**Comment by x3zvawq** [comment]
> boss信息是否可以返回简介

翻了一下伯伯给的文件 似乎并没有这样的文件包含了简介 只能通过fb_boss那个表 用boss名称进行匹配 但是似乎和百战里出现的场景描述会不大一样 不是很靠谱

**Comment by x3zvawq** [comment]
### 【请求性能优化】
types effects这两个接口返回的数据量较少，寻思直接写到前端算了 减少一点请求量
已经丢到assets/data里面了 怎么用的话可能得看一看 有点看不懂你是怎么实现的 或者不改应该问题也不大

**Comment by x3zvawq** [comment]
### 【地图】
#### 交互
地图尽量按照设计稿写 右侧的当前层信息可以整成常驻显示的 进入地图的时候默认显示第一层就可以了
点击地图中任何一个层甚至点击当前层都会导致闪烁一下 可能得找找原因
不需要取消选中 选中一个层在右边看信息的时候也不需要把当前整个地图弄辣么暗
#### 描述
![image](https://github.com/JX3BOX/fb/assets/47066861/5537d5c6-8025-4bca-9951-3ee2fb56335d)
看设计稿来，尽量把描述弄成四个字这样，对齐可能比较好看。我在assets/data/baizhan_effect.js里面的effects里面写好了，直接显示export的effects变量里面effect的tag就可以了。
#### 下载按钮
要不放个位置，比如固定正上方或者正下方 放在右上角可能会和右侧边栏冲突

---
右侧BOSS信息的常驻有个问题，PC和smPc以及notebook，是会导致中间的地图显示不全的。中间地图有固定大小1132*960，只是能缩放。除了在移动端初始化缩小以外，其他时候都是初始scale为1.
选中后没有选中的层数如果不暗的效果是这样的，可能会造成选中效果不明显。
![image](https://github.com/JX3BOX/fb/assets/30660189/93aa1588-d7de-4ef6-819a-8560896643b7)
对比度效果：
![image](https://github.com/JX3BOX/fb/assets/30660189/981d53a8-fc42-4d0d-bb04-34753f57c5a0)
闪烁我瞅瞅，估摸着可能是对比度的问题。
tag我来弄一下，现在改的有点问题。重复了。
![image](https://github.com/JX3BOX/fb/assets/30660189/e8e6f413-190f-4ead-bae3-800a9f4a45e5)
按钮是否可以直接放在左侧
![image](https://github.com/JX3BOX/fb/assets/30660189/c6d92628-688e-4b3d-ba15-7371cf0a6882)

---
右侧常驻信息在1920之上常驻，之下浮动

**Comment by x3zvawq** [comment]
### 【地图/筛选】
筛选是不是应该支持多选，同理上面应该多个清空所有选择项的交互开关
效果和首领都应该有。

#### 效果筛选
根据层效果筛选那里似乎交互有些问题，好像是我改过之后发生的 
但是实在有些没看明白是怎么个操作的

#### 首领筛选
这里是用来筛选的，不要把60个全列出来啊！
只要列出所有存在的首领就可以了， 根据boss那个接口返回的去个重做成列表
然后选中之后在右边展示所有这个首领的格子
不需要显示链接 这个功能可能会砍掉或者先藏起来

---
设计稿的筛选是阶级（被否定，因为一个阶级就是一行），特殊效果（个人理解做的单选，因为额外奖励这个筛选就有30多层，这个筛选条件是人为定义的，有挺多是重复的，且玩家一般也只会关心某一种，再去看另一种）。首领（建议改为百战首领或者本周首领），设计的意思是左侧首领列表为本周的BOSS的列表，方便玩家快速游览或者在其他两个栏目也可以游览。只是说做了左侧与中间的关联效果。

**Comment by x3zvawq** [comment]
### 【评论相关】
如果直接由我们来指定一个boss的攻略链接的话 可能会给作者或者用户带来困扰
所以撑内容的话还是需要做成评论的形式而不是我们来指定链接
但是按照产品的想法我们点赞数等功能我们的通用评论组件并没有支持
做的话无法实现点赞功能 评论应该统一管理会比较好 单独做一套评论的话不太合适
所以我寻思要么直接就用攻略区 要么就是无法点赞的评论

---
攻略链接我直接隐藏掉。
有攻略列表是否还需要评论，或者说在哪里评论是个问题，很明显，如果地图的右侧信息是否脱离文档流的，就不适合评论。要做的话可能就是单独做个BOSS的详情页，问题就是没那么多内容来填充这个页面。
而且评论组件对我来说可能有点难以接入，囧

**Comment by x3zvawq** [comment]
### 【移动端】
移动端体验感觉不是很好优化
用applayout的话适配这个设计有点麻烦
好困啊 再看吧Orz 晚安

---
没有移动端，只有缩放，我勉强搞了个初始缩放能够展示全部的样式。然后用户可以自己放大，不过没啥意义，因为他要看完整有那么大的尺寸，已经默认把下载按钮给他们放到很显眼的位置了。直接下载可能会好一点。囧

**Comment by fifthThirteen** [comment]
BOSS链接去掉

**Comment by nierssaxa** [comment]
### 筛选
1.百战地图取消掉每层首领
2.特殊效果的筛选，要加上全部（默认选上）
3.每层首领的筛选改为首领，并且加上全部（默认选上）
4.所有筛选取消掉图标，仅文字（主要是图标不好找）

### 图层
1.默认背景颜色为 UnSelectBackground #373F5F
2.默认文字颜色为 UnSelectText #C2C3FF
3.被选择或者筛选的背景颜色为，SelectBackground #7879D0
4.被选择或者筛选的文字颜色为，SelectText #DEDDD3
5.头像全部100%透明度展示

代码方面，建议将颜色做一个组件设置（名词不知道，反正就是设置一个映射名字，以后直接用这个名字代替颜色就对了）

**Comment by nierssaxa** [comment]
### 右侧信息
1.当没有层数效果时，层数效果要用【当前层没有特殊效果】来代替
2.技能那边，黑色技能的识别颜色用 #232323 来代替
3.技能鼠标移入的颜色变动为 MouseEnter #B2B3FF
4.攻略默认用 带框按钮形式展示，看figma（注意中文偏差，上距是1，下距是2）

### BUG
当前29层选择后，显示的是30层

**Comment by nierssaxa** [comment]
### 首领信息
暂时先禁选，名字改为即将上线，要改的太多

**Comment by nierssaxa** [comment]
### 技能列表
1.将筛选框拉到左边
2.首领筛选不要做成下拉框

**Comment by nierssaxa** [comment]
筛选按钮
![)A4KAN%BZN0B8H47A3(F`TK](https://github.com/JX3BOX/fb/assets/97571785/58165024-52d8-48f0-af5e-f8a77443e9ba)
1.每行之间10px
2.区分用的类别文字12px
3.所有按钮默认81.33x22 （不好弄可以走81）
4.选择项走Select的颜色系
5.未选择保持原样
6.每个按钮最多支持五个字，如果用恶战日轮山城，则用前四个汉字加上省略号，如 恶战日轮...
7.如果长度不够要滚动，则把筛选两个字固定死，下面的内容区滚动

**Comment by nierssaxa** [comment]
## 筛选
### 逻辑层次
当AB两大类筛选可同时筛选时，已选A1和B2，则显示结果应该是，包含A1+B2的结果（呈缩减），目前为A1所有结果+B2所有结果（呈增加）。注意修改调整。
改动方向：
1.新增分类（在最上面显示）：常用
2.只有一个可选项，且每次加载默认载入该筛选，名字为【特殊效果 & 精英首领】（150x22 px）
3.特殊效果和首领可以组合筛选，常用则不可以，即点击常用的【特殊效果 & 精英首领】后，清空特殊效果和首领的筛选。

### 颜色
未被筛选的颜色没有做切换
1.头像的框 UnSelectBackground #373F5F
2.首领的字 UnSelectText #C2C3FF
3.层数的数字 ~UnSelectText #C2C3FF~ #7879D0
![(@M`WC 24OD`C{Y 54D EJ](https://github.com/JX3BOX/fb/assets/97571785/324b2763-1663-401d-af35-60bafb737bca)

- [x] 已完成

**Comment by nierssaxa** [comment]
## 技能
### 可以先排到后面，看看有没有人愿意维护
### 地图
1.点击首领展示的技能，点击后跳转到技能列表页，而非对应数据库
2.且跳转后自动在左边的筛选填入技能名字
3.可能要做路由，比如 fb/baizhan/skill=2389 类似的让用户可以复制链接转发给别人看的时候可以直接找到这个技能，具体实现方式你们开发商量。
4.技能的信息展示可能要做出常驻（不能全靠悬停，等确认有人维护后根据情况做改动，先mark）

- [ ] 已完成

**Comment by nierssaxa** [comment]
### BUG
1.非特殊层的层，被筛选时层数数字没有显示（应该是颜色设置的问题，没有设置为 SelectText #DEDDD3）

### 筛选逻辑
看看能不能选择【特殊效果&精英首领】的时候，下面两个的【全部首领】和【精英首领】不默认选上。
不然的话，第一次筛选，只想看【额外奖励】的情况下，还要手动点掉【精英首领】，初次使用的人会比较错愕。

### 界面优化
1.左侧筛选和上面的间距调整到15px（原先30px），同时筛选的长度拉到底，保证右边的底部对齐的
2.左侧不要做收起
3.右侧收起按钮的圆角去掉，PS：右侧的圆角应当是左上和左下（不要直接复制左边的代码啊喂）
4.右侧收起后，默认的展开按钮颜色记得改的一致（和收起按钮一样）
5.左侧文本 即将上线 → 首领数据，文本和图标透明度改到30%
6.右侧所有的技能图标大小为35x35px，但只居中展示30x30px（主要是不展示那个边框）
7.右侧被动技能的展示区域改到24x24，并在原先的30x30px处填充背景 #373F5F，最右侧加上被动技能字样
8. @X3ZvaWQ 看下能不能单独区分，既不不是被动也没有破绽的技能（治疗），最右侧加一些图标，鼠标移入时浮窗显示【恢复/提升/防御/召唤等，无法击破破绽的技能】文本
9. 该层没有效果时，画一个78px的区域，居中显示 【当前层没有特殊效果】，不要加粗
10. 文本：掉落 → 技能掉落
11. 特殊层文本：随机次数 → 随机前进
12. 特殊层未被筛选的层数数字颜色改为 #7879D0 （这个好像是我的问题，上一次提的时候颜色没写对）
↑ 5,6,7,8,9,10,12条Figma上已更新

### 交互优化
1. 常规背景色为 UnSelectBackground #373F5F
2. 常规文字色为 UnSelectText #C2C3FF
3. 常规层数文字色为 #7879D0
4. 筛选背景色为 SelectBackground #7879D0
5. 筛选文字色为 SelectText #DEDDD3
6. 筛选层数文字色为 SelectText #DEDDD3
7. 选择层数时，将这个层的配色变为筛选色（456条）。
8. 选择层数时，未被选择的层数透明度全部变到20%，筛选的图层保持变色的情况下透明度变到20%
9. 右侧内容没有做滑动
10. 因为这种改动，所以在首次进入页面时，不要默认选择任何层，没有选择层时，右侧内容为空即可
↑Figma已更新



### 功能
1.需要做个路由？，比如 fb/baizhan/map=1，则地图默认选上第一层。
这个功能是需要配合另一个issue，副本侧边栏百战功能做的，用于实现在那边点击层数后自动跳转到这个页面对应层数。

### 讨论评价→相关攻略
1.短时间内，没法做评论的话，就自动抓取两个最新/置顶的攻略上来。
2.按钮：攻略→查看全部
3.按钮注意右对齐

↑ 1,2,3条Figma上已更新 @X3ZvaWQ @iRuxu 

### 导出优化
1.导出图片的图，右下角新增文本【魔盒·百战查询 https://www.jx3box.com/fb/baizhan 】 30px
↑ Figma已更新样式

- [x] 已完成
