### ISSUE TITLE
百战技能

### ISSUE THREAD

**Issue by fifthThirteen** [JX3BOX/fb#34]
1. 百战技能
![image](https://github.com/JX3BOX/fb/assets/30660189/1eb8a351-3408-4c3a-9b2e-c9d7fa3783e7)
2. 百战BOSS，等新设计稿
3. 百战评论

**Comment by nierssaxa** [comment]
## 左侧

### 文本
1.更新时间和地图的独立开来，取负责人上传数据的时间
2.持续时间整行删除（仅技能数据这边），保留区域空白

### 筛选
全部展开选择是比较方便，但整体实在太长了，如果只想筛选BOSS需要滚动
因此还是做成下拉框减少空间占用
1.效果还是做成下拉框，默认选择全部效果
2.颜色和消耗同理
3.搜索框和下拉框之间不需要做小标题和分割线区分
4.搜索框增加一个放大镜的图标

### figma
已更新左侧 https://www.figma.com/file/28OnUWgiItEcGEBP0daWnL/%E7%99%BE%E6%88%98?type=design&node-id=83%3A381&mode=design&t=RO2dOlBzxvyu5DQS-1

- [ ] 已完成

**Comment by nierssaxa** [comment]
## 中间和右侧
### PC样式
1.保留现有的中间布局（自适应拉宽宽度）
2.将所有不能自动化的列全部砍掉 @X3ZvaWQ 
3.鼠标移入每行时的悬浮效果删除
4.鼠标移入新增效果，在右侧展示技能详细信息，~鼠标点击则固定显示，直到再次点击取消~
5.鼠标点击跳转效果删除
6.每行鼠标移入时，新增一个查看详细数据的按钮，点击跳转到对应数据库页面

### 手机端
1.默认隐藏右侧，点击后右侧弹出，再次点击右侧非按钮区域则隐藏

### Figma （中间部分）
1.样式不要全抄
2.只要注意详细信息的按钮和他跟右边的边距即可

- [x] 已完成

**Comment by nierssaxa** [comment]
## 右侧
### 样式
1.基本复制figma即可（注意被动技能图标变化）
2.使用信息的占用，为30x10的区域，每个图标为10px，居中展示
3.使用信息固定为，【占用】【破绽】【特殊补充】
4.常规技能一般只显示【占用】和【破绽】
5.被动技能/没有破绽的技能一般只显示【占用】和【特殊补充】
6.部分带有破绽的被动技能则三个全部显示

### 技能介绍
1.看看能不能判定换行的时候多空一行，和figma一样，显得整洁一点
2.看看能不能单独判定技能介绍里的<>字段，将其颜色变色，弱化或强化无用信息方便用户阅读
3. 默认为hide.svg，该状态下↑第二条的字段颜色为#7879D0，点击后变为showup.svg，字段颜色为#FBFF47

### 按钮交互
1.中间和右侧的详细数据，默认背景色为#313956
2.鼠标移入后背景色变为#7879D0

- [x] 已完成

**Comment by nierssaxa** [comment]
### 右侧补充
1.文本 使用信息 → 技能信息
2.第一行为【占用】【破绽】【特殊补充】
3.第二行到第五行，固定宽高比为124.5x25 px
4.第一行的高度有变化，从原来的设计稿的19px高变到25
5.技能信息的内容区域的间隔均为15px（每个内容之间，每行之间，第一行是13，以figma为准）

### figma
已更新

- [x] 已完成

**Comment by nierssaxa** [comment]
## 优化
### 筛选
1.文本，白色 → 无颜色招式
2.首领筛选，在最后新增【未知】

### 中间
1.详细数据的按钮文本居中
2.适配小屏的时候，依次砍掉：按钮列 → 首领列 → 占用列 → 破绽列 ，最小屏（手机）时只保留技能列和效果列
3.取消掉单次点击后固定的效果
4.展示没有首领的技能，用【-】代替

### 右侧
1.技能信息的第一行三个内容，大小宽度走figma样式，不要拉宽宽度
2.如果遇到超出长度时，避免出现技能信息那边一行一个效果的情况（可以减少每行内容之间的间距）
3.技能介绍的标题与内容之间的间隔缩短到10px
4.技能名字扩大到24px，上方加入技能ID
5.所有被动技能用60px #313956 背景+50px原型图标
6.所有常规技能，直接拉取对应图标60px
7.部分没法明确首领的技能，掉落来源处 画一个30px高度的区域，居中填写 【未知】 14px #C8C8C8
↑3456条已更新到figma，第6条在设计图右边
![`586X3`KB0SCCF14X`)TUFG](https://github.com/JX3BOX/fb/assets/97571785/10ee8c2c-d858-4a1e-87d1-1764f6e08f12)

- [x] 已完成
---
1.详细数据的按钮文本居中 是居中的，但是某些小尺寸下不会居中
