### ISSUE TITLE
首领数据

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/fb#35]
等新设计稿

**Comment by nierssaxa** [comment]
## Main

### 功能
1.快速展现BOSS技能掉落
2.快速展现BOSS本周位置
3.拉取BOSS文章
4.评论还是删掉

### 设计稿

https://www.figma.com/file/28OnUWgiItEcGEBP0daWnL/%E7%99%BE%E6%88%98?type=design&node-id=83%3A381&mode=design&t=Axc8DipWQpzliHe5-1

**Comment by nierssaxa** [comment]
## 左侧

### 顶部
1.和技能列表一样，空白区域用百战异闻录的svg代替
2.注意将透明度调回100%

### 筛选 （变更为菜单功能）
1.文本：【筛选】→ 【快速选择】
2.搜索框效果变更为输入BOSS名字后，在下面的BOSS列表里高亮显示（注意跟已选择的颜色区分）
3.BOSS列表，点击后直接展示对应boss内容
4.BOSS列表，在第一个位置，新增【通用】（读取的攻略为分类“其他”）

- [x] 已完成

**Comment by nierssaxa** [comment]
## 中间
1.大致跟地图的右侧差不多
2.头像放大到70px
3.层数文本更替为【首领】【精英首领】
4.新增一个本周出现位置，以及持续时间
5.出现位置需要高亮，以及层数数字显示

- [x] 已完成

**Comment by nierssaxa** [comment]
## 右侧
1.注意右上角的按钮背景色变化
2.内容直接拉取现在的副本列表页样式就行
3.宽度自适应拉伸本区域

- [x] 已完成

**Comment by nierssaxa** [comment]
## 手机适配
1.砍掉中间的技能掉落和本周出现位置的内容
2.将中间和右边变为上下结构
3.将中间宽度拉伸至适配屏幕
4.文章展示样式变更

- [x] 已完成
