### ISSUE TITLE
建议修改筛选功能的样式

### ISSUE THREAD

**Issue by ghost** [JX3BOX/fb#8]
![Snipaste_2020-05-25_19-18-05.png](https://i.loli.net/2020/05/25/gb1I5dCRM6yKBjo.png)

也许这个做的并不是按钮而是背景，但是容易让用户误解它就是按钮。
然而按钮内存在勾选项，确实有些违和，建议去掉这个背景。

**Comment by fakedestinyck** [comment]
没有看懂

**Comment by ghost** [comment]
> 没有看懂

![Snipaste_2020-05-27_02-00-19.png](https://i.loli.net/2020/05/27/qbXUidoOr2ElD5a.png)
你和上面的图对比下

**Comment by iRuxu** [comment]
已完成
